const LEFT_POINTING_ANGLE_BRACKET = "&lsaquo;";
const DOUBLE_LEFT_POINTING_ANGLE_BRACKET = "&laquo;";
const RIGHT_POINTING_ANGLE_BRACKET = "&rsaquo;";
const DOUBLE_RIGHT_POINTING_ANGLE_BRACKET = "&raquo;";
const ANOTHER_CONSTANT = "SomeValue";

const constants = {
  LEFT_POINTING_ANGLE_BRACKET,
  DOUBLE_LEFT_POINTING_ANGLE_BRACKET,
  RIGHT_POINTING_ANGLE_BRACKET,
  DOUBLE_RIGHT_POINTING_ANGLE_BRACKET,
  ANOTHER_CONSTANT,
  // Add other constants as needed
};

export default constants;